[theme]
primaryColor = "#6366F1"
backgroundColor = "#eef2ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "simpletest.pro"
serverPort = 443
